import { Octokit } from '@octokit/rest';
import { GoogleGenAI } from '@google/genai';

export default async function handler(req, res) {
  // 1. Verify Vercel Cron authorization secret
  const authHeader = req.headers.authorization;
  const cronSecret = process.env.CRON_SECRET;
  
  if (process.env.NODE_ENV === 'production') {
    if (!cronSecret || authHeader !== `Bearer ${cronSecret}`) {
      return res.status(401).json({ error: 'Unauthorized cron request.' });
    }
  } else if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
    return res.status(401).json({ error: 'Unauthorized cron request.' });
  }

  // Check required environment variables
  const githubToken = process.env.GITHUB_TOKEN;
  const geminiApiKey = process.env.GEMINI_API_KEY;

  if (!githubToken) {
    return res.status(500).json({ error: 'Missing GITHUB_TOKEN environment variable.' });
  }

  if (!geminiApiKey) {
    return res.status(500).json({ error: 'Missing GEMINI_API_KEY environment variable.' });
  }

  const owner = process.env.GITHUB_OWNER || 'eduardodarocha';
  const repo = process.env.GITHUB_REPO || 'nextjs-blog';
  const defaultBranch = process.env.GITHUB_BRANCH || 'main';

  const octokit = new Octokit({ auth: githubToken });
  const ai = new GoogleGenAI({ apiKey: geminiApiKey });

  try {
    // 2. Fetch existing posts from GitHub repository to avoid duplicate topics
    let existingFiles = [];
    try {
      const { data } = await octokit.repos.getContent({
        owner,
        repo,
        path: 'posts',
        ref: defaultBranch,
      });
      if (Array.isArray(data)) {
        existingFiles = data.map((file) => file.name);
      }
    } catch (e) {
      console.warn('Could not fetch existing posts list:', e.message);
    }

    // 3. Build prompt for Gemini API (Portuguese & AI Ecosystem Niche)
    const prompt = `Você é um especialista em Inteligência Artificial, Engenharia de Software e Tecnologias Emergentes.
Sua tarefa é escrever um artigo completo, didático e altamente relevante em PORTUGUÊS DO BRASIL sobre o ecossistema de Inteligência Artificial.

REGRAS:
1. O artigo DEVE ser em Português do Brasil.
2. O tema deve ser estritamente focado no ecossistema de IA (por exemplo: Agentes Autônomos de IA, Modelos de Linguagem (LLMs), RAG (Retrieval-Augmented Generation), Visão Computacional, Engenharia de Prompt, Modelos Open-Source, IA na programação, IA no cotidiano ou Ética em IA).
3. Não repita estes tópicos existentes no blog: ${existingFiles.join(', ')}.
4. O conteúdo deve ser rico em detalhes, com títulos (##, ###), exemplos práticos, blocos de código se aplicável, e uma conclusão instigante.

FORMATO DE RESPOSTA (Retorne EXATAMENTE um JSON válido sem marcações markdown extra em volta):
{
  "title": "Título atraente do artigo em Português",
  "slug": "slug-do-artigo-em-kebab-case",
  "content": "Conteúdo completo em Markdown..."
}`;

    // Call Gemini API with JSON mode
    const aiResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
      },
    });

    let rawText = aiResponse.text || '';
    // Clean potential ```json codeblocks around Gemini JSON output
    rawText = rawText.replace(/```json/gi, '').replace(/```/g, '').trim();

    let articleData;
    try {
      articleData = JSON.parse(rawText);
    } catch (parseError) {
      return res.status(500).json({
        error: 'Failed to parse JSON response from Gemini API',
        rawText,
      });
    }

    const { title, slug, content } = articleData;

    if (!title || !slug || !content) {
      return res.status(500).json({
        error: 'Incomplete article data generated by AI.',
        articleData,
      });
    }

    const todayDate = new Date().toISOString().split('T')[0];
    const cleanSlug = slug.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');
    const filePath = `posts/${cleanSlug}.md`;

    const fullMarkdownContent = `---
title: '${title.replace(/'/g, "''")}'
date: '${todayDate}'
---

${content}
`;

    // 4. Create Git Branch and Commit on GitHub
    // Step A: Get main branch SHA
    const { data: mainRef } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const mainSha = mainRef.object.sha;

    // Step B: Create a unique branch name for the Pull Request
    const newBranchName = `draft/ia-post-${cleanSlug}-${Date.now()}`;
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${newBranchName}`,
      sha: mainSha,
    });

    // Step C: Create the post file on the new branch
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: filePath,
      message: `feat(blog): adicionei novo post em português sobre IA - "${title}"`,
      content: Buffer.from(fullMarkdownContent, 'utf-8').toString('base64'),
      branch: newBranchName,
    });

    // Step D: Open a Pull Request into main branch
    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: `🤖 Novo Post sobre IA: ${title}`,
      head: newBranchName,
      base: defaultBranch,
      body: `### 🤖 Artigo Gerado Automaticamente por IA

**Título:** ${title}  
**Data:** ${todayDate}  
**Arquivo:** \`${filePath}\`  

---

#### Resumo / Prévia:
${content.substring(0, 300)}...

---
*Revise o conteúdo e clique em **Merge pull request** para publicar no Vercel.*`,
    });

    return res.status(200).json({
      success: true,
      message: 'Post em Português sobre IA gerado com sucesso e Pull Request criado!',
      title,
      slug: cleanSlug,
      branch: newBranchName,
      prUrl: pr.html_url,
    });
  } catch (error) {
    console.error('Error generating daily post:', error);
    return res.status(500).json({
      error: error.message || 'Erro ao gerar post via Vercel Cron.',
    });
  }
}
